#!/bin/sh


p="$(pwd)"
cd "$(git rev-parse --show-toplevel)"

# This git command tells whether git would print colorful output or not.
# If git prints colorful outputs we will do so, too.
if git config --get-colorbool color.ui; then
    Green="\033[32m"
    Red="\033[31m"
    Cyan="\033[0;36m"
    Color_Off="\033[0m"
else
    Green=
    Red=
    Cyan=
    Color_Off=
fi

echo_green() {
    echo -e "${Cyan}[pre-commit]:${Color_Off} ${Green}$*${Color_Off}"
}

echo_red() {
    echo -e "${Cyan}[pre-commit]:${Color_Off} ${Red}$*${Color_Off}"
}

echo_cyan() {
    echo -e "${Cyan}[pre-commit]: $*${Color_Off}"
}

die() {
    echo_red "$*"
    exit 1
}

for i in astyle cmake ctest diff make
do
    if ! type $i 2> /dev/null
    then
        echo_red "No '$i' found, please install or put it in PATH"
        die "You cannot commit"
    fi
done

echo_cyan "Starting test build"

if [ ! -f ./Makefile ]; then
    cmake -DHARD_MODE=ON . || die "Cmake setup failed"
fi

make $MAKEOPTS || die "Failed to build library"
make $MAKEOPTS paper || die "Failed to build paper"

echo_cyan "Successfully passed build test"
echo_cyan "Starting checks for the library"

ctest -VV . || die "the checks for the library failed"

echo_cyan "Successfully passed library checks"

tmpdir=/tmp/git-pre-commit-hook-$$

mkdir -p $tmpdir

bad=0

echo_cyan "Starting astyle check in '$tmpdir'"

oldifs="$IFS"
IFS=$'\n'
for file in $(git diff --name-only HEAD | grep "\.[ch]$")
do
    echo_cyan "Checking: $file"
    fpath="$tmpdir/$(basename "$file")"
    fpath_formatted="$tmpdir/$(basename "$file")-formatted"

    cp "$file" "$fpath"

    astyle --options=./etc/astylerc < "$fpath" > "$fpath_formatted"
    # delete last line of $fpath_formatted
    sed -i '$ d' "$fpath_formatted"

    if ! diff "$fpath" "$fpath_formatted" > /dev/null
    then
        echo_red "Format bad: $file"
        bad=1
    else
        echo_green "Format ok: $file"
    fi

    echo_cyan "Check on $file done, rm '$fpath', '$fpath_formatted'"
    rm "$fpath" "$fpath_formatted"
done
IFS="$oldifs"

echo_cyan "Check done, rm -rf '$tmpdir'"
rm -rf $tmpdir

cd "$p"
[ $bad -eq 1 ] && die "Bad formatted file found. You cannot commit"

exit 0
